In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 102.0, 52.0 ,0.0],
              [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 102.   52.    0. ]
 [  1.8 135.   99.    0.9]]


In [2]:
cal = A.sum(axis=0)  # 竖直轴是0，水平轴是1
print(cal)

[ 59.  237.  155.4  68.9]


In [3]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 98.69375907]
 [ 2.03389831 43.03797468 33.46203346  0.        ]
 [ 3.05084746 56.96202532 63.70656371  1.30624093]]


In [4]:
#另一个例子
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
B = np.array([100, 200, 300])
C = A + B
print(C)

[[101 202 303]
 [104 205 306]
 [107 208 309]]
